language: ruby
rvm:
  - ruby-1.9.3-p551
  - ruby-2.1.9
  - ruby-2.2.5
  - ruby-2.3.1
  - ruby-head
  - rbx-2
  - rbx
  - jruby-19mode
  - jruby-9.0.5.0
  - jruby-head
sudo: false
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx
